# Generated by Django 6.0.6 on 2026-06-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='permisos',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='usuariomodulo',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='usuariomodulo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usuariomodulo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usuariomodulo',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='usuariomodulo',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='usuariomodulo',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
        migrations.DeleteModel(
            name='UsuarioModulo',
        ),
    ]
