# Generated by Django 6.0.6 on 2026-07-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalunidadorganizacional',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalunidadorganizacional',
            name='lft',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalunidadorganizacional',
            name='rght',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalunidadorganizacional',
            name='tree_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unidadorganizacional',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unidadorganizacional',
            name='lft',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unidadorganizacional',
            name='rght',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unidadorganizacional',
            name='tree_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
