# Generated by Django 6.0.6 on 2026-07-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_historicalunidadorganizacional_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidadorganizacional',
            name='es_departamento',
            field=models.BooleanField(default=False, verbose_name='Es departamento'),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='es_departamento',
            field=models.BooleanField(default=False, verbose_name='Es departamento'),
        ),
    ]
