# Generated by Django 6.0.6 on 2026-07-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalunidadorganizacional_es_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidadorganizacional',
            name='es_subdepartamento',
            field=models.BooleanField(default=False, verbose_name='Es Subdepartamento'),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='es_subdepartamento',
            field=models.BooleanField(default=False, verbose_name='Es Subdepartamento'),
        ),
        migrations.AlterField(
            model_name='historicalunidadorganizacional',
            name='es_departamento',
            field=models.BooleanField(default=False, verbose_name='Es Departamento'),
        ),
        migrations.AlterField(
            model_name='unidadorganizacional',
            name='es_departamento',
            field=models.BooleanField(default=False, verbose_name='Es Departamento'),
        ),
    ]
