# Generated by Django 6.0.6 on 2026-07-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicalunidadorganizacional_es_subdepartamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direcciones_modelo', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicaldireccion',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
    ]
