# Generated by Django 6.0.6 on 2026-07-23 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_direccion_establecimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_remitente', models.CharField(max_length=200, verbose_name='Nombre del Remitente')),
                ('email_remitente', models.EmailField(max_length=254, verbose_name='Email del Remitente')),
                ('smtp_host', models.CharField(max_length=255, verbose_name='Host SMTP')),
                ('smtp_port', models.PositiveIntegerField(verbose_name='Puerto SMTP')),
                ('smtp_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('smtp_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('smtp_usuario', models.CharField(max_length=255, verbose_name='Usuario SMTP')),
                ('_smtp_password', models.TextField(db_column='smtp_password', verbose_name='Contraseña SMTP')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('establecimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_correo', to='core.establecimiento', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Configuración de Correo',
                'verbose_name_plural': 'Configuraciones de Correo',
            },
        ),
        migrations.CreateModel(
            name='RecuperacionPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('utilizado', models.BooleanField(default=False)),
                ('fecha_utilizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('UTILIZADO', 'Utilizado'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_solicitud', models.TextField(blank=True, null=True)),
                ('navegador_solicitud', models.CharField(blank=True, max_length=100, null=True)),
                ('version_navegador_solicitud', models.CharField(blank=True, max_length=50, null=True)),
                ('sistema_operativo_solicitud', models.CharField(blank=True, max_length=100, null=True)),
                ('dispositivo_solicitud', models.CharField(blank=True, max_length=100, null=True)),
                ('es_pc_solicitud', models.BooleanField(default=False)),
                ('es_tablet_solicitud', models.BooleanField(default=False)),
                ('es_movil_solicitud', models.BooleanField(default=False)),
                ('es_bot_solicitud', models.BooleanField(default=False)),
                ('ip_utilizacion', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_utilizacion', models.TextField(blank=True, null=True)),
                ('navegador_utilizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('version_navegador_utilizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('sistema_operativo_utilizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('dispositivo_utilizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('es_pc_utilizacion', models.BooleanField(default=False)),
                ('es_tablet_utilizacion', models.BooleanField(default=False)),
                ('es_movil_utilizacion', models.BooleanField(default=False)),
                ('es_bot_utilizacion', models.BooleanField(default=False)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('solicitud_exitosa', models.BooleanField(default=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.establecimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones_password', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recuperación de Contraseña',
                'verbose_name_plural': 'Recuperaciones de Contraseña',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['token_hash'], name='core_recupe_token_h_a7901d_idx'), models.Index(fields=['estado'], name='core_recupe_estado_b44a2a_idx')],
            },
        ),
    ]
