# Generated by Django 6.0.6 on 2026-06-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historicaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
    ]
