# Generated by Django 6.0.6 on 2026-08-03 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicaluser_last_login_browser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='last_login_browser',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='last_login_browser_version',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='last_login_device',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='last_login_ip',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='last_login_os',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_browser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_browser_version',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_device',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_os',
        ),
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('equipo', models.CharField(blank=True, max_length=150, null=True)),
                ('navegador', models.CharField(blank=True, max_length=50, null=True)),
                ('version_navegador', models.CharField(blank=True, max_length=30, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=50, null=True)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.establecimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Acceso',
                'verbose_name_plural': 'Historiales de Accesos',
                'ordering': ['-fecha_acceso'],
            },
        ),
    ]
