# Generated by Django 6.0.6 on 2026-06-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_departamento_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodulo',
            name='consulta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='modulo',
            name='consulta',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
