# Generated by Django 6.0.6 on 2026-08-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_historicaluser_last_login_browser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='funcionario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.funcionario', verbose_name='Funcionario'),
        ),
        migrations.AddField(
            model_name='user',
            name='funcionario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='core.funcionario', verbose_name='Funcionario'),
        ),
    ]
