# Generated by Django 6.0.6 on 2026-06-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_historicalpuestotrabajo_puestotrabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='historicalfuncionario',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalfuncionario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
