# Generated by Django 6.0.6 on 2026-06-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_funcionario_establecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='NO INFORMADO',
                                   max_length=15, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='historicalfuncionario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='NO INFORMADO',
                                   max_length=15, verbose_name='Sexo'),
        ),
    ]
