# Generated by Django 6.0.6 on 2026-06-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_funcionario_sexo_historicalfuncionario_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='historicalfuncionario',
            name='rut',
            field=models.CharField(db_index=True, max_length=12, verbose_name='RUT'),
        ),
    ]
