# Generated by Django 6.0.6 on 2026-06-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_funcionario_rut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='puesto_trabajo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='historicalfuncionario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='historicalfuncionario',
            name='puesto_trabajo',
        ),
        migrations.RemoveField(
            model_name='historicalfuncionario',
            name='sexo',
        ),
    ]
