# Generated by Django 6.0.6 on 2026-06-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_funcionario_fecha_nacimiento_and_more'),
        ('soporte', '0005_remove_historicalticket_funcionario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfuncionario',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalfuncionario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='historicalfuncionario',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='historicalfuncionario',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfuncionario',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalpuestotrabajo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalpuestotrabajo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpuestotrabajo',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='puestotrabajo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='puestotrabajo',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='HistoricalFuncionario',
        ),
        migrations.DeleteModel(
            name='HistoricalPuestoTrabajo',
        ),
        migrations.DeleteModel(
            name='PuestoTrabajo',
        ),
    ]
