# Generated by Django 6.0.6 on 2026-06-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_historicalfuncionario_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='departamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.departamento', verbose_name='Departamento'),
        ),
    ]
