# Generated by Django 6.0.6 on 2026-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_historicaluser_departamento_user_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='alias',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalestablecimiento',
            name='alias',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
