# Generated by Django 6.0.6 on 2026-06-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_establecimiento_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodulo',
            name='en_mantenimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulo',
            name='en_mantenimiento',
            field=models.BooleanField(default=False),
        ),
    ]
