# Generated by Django 6.0.6 on 2026-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_historicalmodulo_en_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodulo',
            name='mantenimiento_hasta',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='mantenimiento_hasta',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
