# Generated by Django 6.0.6 on 2026-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historicalmodulo_mantenimiento_hasta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmodulo',
            name='icono',
            field=models.TextField(blank=True, help_text='\n        <p><strong>Formato esperado:</strong></p>\n\n        <pre style="background:#f5f5f5;padding:10px;border-radius:4px;overflow:auto;">\n    &lt;svg class="small-box-icon" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"&gt;\n        &lt;path d="PEGAR_AQUI_EL_PATH"/&gt;\n    &lt;/svg&gt;\n        </pre>\n\n        <p>\n            Solo debe reemplazar el valor del atributo <code>d</code> del elemento\n            <code>&lt;path&gt;</code>.\n        </p>\n\n        <p>\n            Puede obtener el <strong>path</strong> desde\n            <a href="https://heroicons.com/" target="_blank">Heroicons</a>\n            (copiando únicamente el contenido del atributo <code>d</code>).\n        </p>\n        '),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='icono',
            field=models.TextField(blank=True, help_text='\n        <p><strong>Formato esperado:</strong></p>\n\n        <pre style="background:#f5f5f5;padding:10px;border-radius:4px;overflow:auto;">\n    &lt;svg class="small-box-icon" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"&gt;\n        &lt;path d="PEGAR_AQUI_EL_PATH"/&gt;\n    &lt;/svg&gt;\n        </pre>\n\n        <p>\n            Solo debe reemplazar el valor del atributo <code>d</code> del elemento\n            <code>&lt;path&gt;</code>.\n        </p>\n\n        <p>\n            Puede obtener el <strong>path</strong> desde\n            <a href="https://heroicons.com/" target="_blank">Heroicons</a>\n            (copiando únicamente el contenido del atributo <code>d</code>).\n        </p>\n        '),
        ),
    ]
