# Generated by Django 6.0.6 on 2026-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_historicalmodulo_icono_alter_modulo_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestablecimiento',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
