# Generated by Django 6.0.6 on 2026-07-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_establecimiento_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodulo',
            name='es_clinico',
            field=models.BooleanField(default=False, verbose_name='Es clínico'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='es_clinico',
            field=models.BooleanField(default=False, verbose_name='Es clínico'),
        ),
    ]
