# Generated by Django 6.0.6 on 2026-07-04 17:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_historicalmodulo_es_clinico_modulo_es_clinico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodulo',
            name='texto_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=[('#ffffff', 'Blanco'), ('#000000', 'Negro')], verbose_name='Color de texto'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='texto_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=[('#ffffff', 'Blanco'), ('#000000', 'Negro')], verbose_name='Color de texto'),
        ),
    ]
