# Generated by Django 6.0.6 on 2026-07-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_historicalmodulo_texto_color_modulo_texto_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='departamento',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='El departamento debe pertenecer al establecimiento seleccionado.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='El establecimiento debe ser consistente con el departamento seleccionado.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='El departamento debe pertenecer al establecimiento seleccionado.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='establecimiento',
            field=models.ForeignKey(blank=True, help_text='El establecimiento debe ser consistente con el departamento seleccionado.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.establecimiento', verbose_name='Establecimiento'),
        ),
    ]
