# Generated by Django 6.0.6 on 2026-07-09 12:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_historicaluser_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmodulo',
            name='color',
            field=colorfield.fields.ColorField(default='#006FB3', image_field=None, max_length=25, samples=[('#006FB3', 'Primary (Azul)'), ('#7F8F99', 'Secondary (Gris)'), ('#3fa1ad', 'Success (Verde)'), ('#876bbe', 'Info (Morado)'), ('#FFA11B', 'Warning (Naranja)'), ('#1976D2', 'Azul Corporativo'), ('#1565C0', 'Azul Oscuro'), ('#0097A7', 'Turquesa'), ('#2E7D32', 'Verde'), ('#43A047', 'Verde Claro'), ('#7CB342', 'Lima'), ('#F57C00', 'Naranjo'), ('#FFB300', 'Ámbar'), ('#D32F2F', 'Rojo'), ('#C62828', 'Burdeo'), ('#8E24AA', 'Morado'), ('#5E35B1', 'Violeta'), ('#3949AB', 'Índigo'), ('#455A64', 'Gris Oscuro'), ('#607D8B', 'Gris')]),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='color',
            field=colorfield.fields.ColorField(default='#006FB3', image_field=None, max_length=25, samples=[('#006FB3', 'Primary (Azul)'), ('#7F8F99', 'Secondary (Gris)'), ('#3fa1ad', 'Success (Verde)'), ('#876bbe', 'Info (Morado)'), ('#FFA11B', 'Warning (Naranja)'), ('#1976D2', 'Azul Corporativo'), ('#1565C0', 'Azul Oscuro'), ('#0097A7', 'Turquesa'), ('#2E7D32', 'Verde'), ('#43A047', 'Verde Claro'), ('#7CB342', 'Lima'), ('#F57C00', 'Naranjo'), ('#FFB300', 'Ámbar'), ('#D32F2F', 'Rojo'), ('#C62828', 'Burdeo'), ('#8E24AA', 'Morado'), ('#5E35B1', 'Violeta'), ('#3949AB', 'Índigo'), ('#455A64', 'Gris Oscuro'), ('#607D8B', 'Gris')]),
        ),
    ]
