# Generated by Django 6.0.6 on 2026-07-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_historicalmodulo_color_alter_modulo_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='departamento',
        ),
    ]
