# Generated by Django 6.0.6 on 2026-07-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_departamento_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nombre'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'ordering': ['nombre'], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='historicalcargo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Cargo', 'verbose_name_plural': 'historical Cargos'},
        ),
        migrations.AlterModelOptions(
            name='historicaldireccion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Dirección', 'verbose_name_plural': 'historical Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='historicalprofesion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Profesión', 'verbose_name_plural': 'historical Profesiones'},
        ),
        migrations.AlterModelOptions(
            name='historicalrolorganizacional',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Rol Organizacional', 'verbose_name_plural': 'historical Roles Organizacionales'},
        ),
        migrations.AlterModelOptions(
            name='historicalubicacion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Ubicación', 'verbose_name_plural': 'historical Ubicaciones'},
        ),
        migrations.AlterModelOptions(
            name='historicalunidadorganizacional',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Unidad Organizacional', 'verbose_name_plural': 'historical Unidades Organizacionales'},
        ),
        migrations.AlterModelOptions(
            name='profesion',
            options={'ordering': ['nombre'], 'verbose_name': 'Profesión', 'verbose_name_plural': 'Profesiones'},
        ),
        migrations.AlterModelOptions(
            name='rolorganizacional',
            options={'ordering': ['nombre'], 'verbose_name': 'Rol Organizacional', 'verbose_name_plural': 'Roles Organizacionales'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterModelOptions(
            name='unidadorganizacional',
            options={'verbose_name': 'Unidad Organizacional', 'verbose_name_plural': 'Unidades Organizacionales'},
        ),
    ]
