# Generated by Django 6.0.6 on 2026-07-10 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0027_alter_cargo_options_alter_direccion_options_and_more'),
        ('soporte', '0016_remove_historicalticket_departamento_and_more'),
        ('gestion_tic', '0002_remove_celular_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldepartamento',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaldepartamento',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='historicaldepartamento',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldepartamento',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Actualizado Por'),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='HistoricalDepartamento',
        ),
    ]
