# Generated by Django 6.0.6 on 2026-07-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_historicaldepartamento_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidadorganizacional',
            name='nombre',
            field=models.CharField(default='SIN NOMBRE', max_length=200),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='nombre',
            field=models.CharField(default='SIN NOMBRE', max_length=200),
        ),
    ]
