# Generated by Django 6.0.6 on 2026-07-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_historicalunidadorganizacional_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='unidad_organizacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='core.unidadorganizacional', verbose_name='Unidad Organizacional'),
        ),
        migrations.AddField(
            model_name='historicalfuncionario',
            name='unidad_organizacional',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.unidadorganizacional', verbose_name='Unidad Organizacional'),
        ),
    ]
