# Generated by Django 6.0.6 on 2026-07-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_funcionario_unidad_organizacional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidadorganizacional',
            name='unidad_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='unidad_principal',
            field=models.BooleanField(default=False),
        ),
    ]
