# Generated by Django 6.0.6 on 2026-07-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_historicalunidadorganizacional_unidad_principal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['-id'], 'verbose_name': 'Funcionario', 'verbose_name_plural': 'Funcionarios'},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalfuncionario',
            name='user',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nombres',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Rut'),
        ),
        migrations.AddField(
            model_name='historicalfuncionario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='historicalfuncionario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='historicalfuncionario',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='historicalfuncionario',
            name='nombres',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='historicalfuncionario',
            name='rut',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, verbose_name='Rut'),
        ),
    ]
