# Generated by Django 6.0.6 on 2026-07-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_funcionario_options_remove_funcionario_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='historicalfuncionario',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo'),
        ),
    ]
