# Generated by Django 6.0.6 on 2026-07-14 00:04

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_funcionario_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidadorganizacional',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalunidadorganizacional',
            name='lft',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalunidadorganizacional',
            name='rght',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalunidadorganizacional',
            name='tree_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='lft',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='rght',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='tree_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalunidadorganizacional',
            name='padre',
            field=mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.unidadorganizacional'),
        ),
        migrations.AlterField(
            model_name='unidadorganizacional',
            name='padre',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='core.unidadorganizacional'),
        ),
    ]
