# Generated by Django 6.0.6 on 2026-07-14 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_historicalunidadorganizacional_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalubicacion',
            name='enlace_google_maps',
            field=models.URLField(blank=True, help_text="Pegue aquí el enlace de Google Maps. Puede ser la dirección buscada o las coordenadas. Para obtener el enlace exacto, busque la dirección en Google Maps, haga clic en 'Compartir' y copie el enlace. También puede usar el enlace de 'Insertar un mapa' para el visor detallado.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalunidadorganizacional',
            name='ubicacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ubicacion'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='enlace_google_maps',
            field=models.URLField(blank=True, help_text="Pegue aquí el enlace de Google Maps. Puede ser la dirección buscada o las coordenadas. Para obtener el enlace exacto, busque la dirección en Google Maps, haga clic en 'Compartir' y copie el enlace. También puede usar el enlace de 'Insertar un mapa' para el visor detallado.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='core.ubicacion'),
        ),
    ]
