# Generated by Django 6.0.6 on 2026-07-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_historicalubicacion_enlace_google_maps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalubicacion',
            name='enlace_google_maps',
            field=models.URLField(blank=True, help_text='Pegue aquí el enlace de Google Maps. Puede ser el enlace de \'Compartir\' o el de \'Insertar un mapa\'. Para obtener mejores resultados: 1. Busque la dirección en Google Maps. 2. Haga clic en \'Compartir\'. 3. Seleccione \'Insertar un mapa\' y copie solo el contenido entre comillas de \'src="..."\'. Si pega el enlace normal de compartir, se mostrará un botón para abrirlo externamente.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='enlace_google_maps',
            field=models.URLField(blank=True, help_text='Pegue aquí el enlace de Google Maps. Puede ser el enlace de \'Compartir\' o el de \'Insertar un mapa\'. Para obtener mejores resultados: 1. Busque la dirección en Google Maps. 2. Haga clic en \'Compartir\'. 3. Seleccione \'Insertar un mapa\' y copie solo el contenido entre comillas de \'src="..."\'. Si pega el enlace normal de compartir, se mostrará un botón para abrirlo externamente.', max_length=1000, null=True),
        ),
    ]
