# Generated by Django 6.0.6 on 2026-07-14 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_historicalubicacion_enlace_google_maps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalubicacion',
            name='enlace_google_maps',
        ),
        migrations.RemoveField(
            model_name='historicalunidadorganizacional',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='enlace_google_maps',
        ),
        migrations.RemoveField(
            model_name='unidadorganizacional',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='direccion',
            name='enlace_google_maps',
            field=models.URLField(blank=True, help_text='Pegue aquí el enlace de Google Maps. Puede ser el enlace de \'Compartir\' o el de \'Insertar un mapa\'. Para obtener mejores resultados: 1. Busque la dirección en Google Maps. 2. Haga clic en \'Compartir\'. 3. Seleccione \'Insertar un mapa\' y copie solo el contenido entre comillas de \'src="..."\'. Si pega el enlace normal de compartir, se mostrará un botón para abrirlo externamente.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicaldireccion',
            name='enlace_google_maps',
            field=models.URLField(blank=True, help_text='Pegue aquí el enlace de Google Maps. Puede ser el enlace de \'Compartir\' o el de \'Insertar un mapa\'. Para obtener mejores resultados: 1. Busque la dirección en Google Maps. 2. Haga clic en \'Compartir\'. 3. Seleccione \'Insertar un mapa\' y copie solo el contenido entre comillas de \'src="..."\'. Si pega el enlace normal de compartir, se mostrará un botón para abrirlo externamente.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalunidadorganizacional',
            name='direccion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.direccion'),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to='core.direccion'),
        ),
    ]
