# Generated by Django 6.0.6 on 2026-07-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_historicalubicacion_enlace_google_maps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcargo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalcargo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcargo',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='HistoricalCargo',
        ),
    ]
