# Generated by Django 6.0.6 on 2026-07-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceso',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='perfilhoros',
            name='acceso',
            field=models.ManyToManyField(blank=True, to='horos.acceso'),
        ),
    ]
