# Generated by Django 6.0.7 on 2026-08-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egresopagoviatico',
            options={'ordering': ['-ano_egreso', '-numero_egreso'], 'verbose_name': 'Egreso y Pago de Viático', 'verbose_name_plural': 'Egresos y Pagos de Viáticos'},
        ),
        migrations.AlterModelOptions(
            name='rendicioncometido',
            options={'ordering': ['-fecha_rendicion', '-id'], 'verbose_name': 'Rendición de Cometido y Cuentas', 'verbose_name_plural': 'Rendiciones de Cometidos y Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='validacionrelojcontrol',
            options={'ordering': ['-fecha_inicio_ausencia', '-id'], 'verbose_name': 'Corte de Asistencia / Reloj Control', 'verbose_name_plural': 'Cortes de Asistencia / Reloj Control'},
        ),
        migrations.AlterField(
            model_name='historicalsolicitudcometidoviatico',
            name='tipo_solicitud',
            field=models.CharField(choices=[('VIATICO', 'Viático'), ('COMETIDO', 'Cometido')], default='COMETIDO_VIATICO', max_length=30, verbose_name='Tipo de Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudcometidoviatico',
            name='tipo_solicitud',
            field=models.CharField(choices=[('VIATICO', 'Viático'), ('COMETIDO', 'Cometido')], default='COMETIDO_VIATICO', max_length=30, verbose_name='Tipo de Solicitud'),
        ),
    ]
