# Generated by Django 6.0.7 on 2026-07-24 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracioncorreo_recuperacionpassword'),
        ('gestion_tic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalcategoria',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicaljefetic',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicallicenciaos',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalmarca',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalmicrosoftoffice',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalmodelo',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalpropietario',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalpuestotrabajo',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalsistemaoperativo',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalsubcategoria',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicaltipocelular',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicaltipocomputador',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicaltipoimpresora',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicaltoner',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='jefetic',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='licenciaos',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='marca',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='microsoftoffice',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='modelo',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='puestotrabajo',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='sistemaoperativo',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='tipocelular',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='tipocomputador',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='tipoimpresora',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='toner',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='ips',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
    ]
