# Generated by Django 6.0.7 on 2026-07-24 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0002_categoria_establecimiento_contrato_establecimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='historicalsubcategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='historicalcategoria',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalcategoria',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='historicalcategoria',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcategoria',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalpuestotrabajo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalpuestotrabajo',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='historicalpuestotrabajo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpuestotrabajo',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalsistemaoperativo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalsistemaoperativo',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='historicalsistemaoperativo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsistemaoperativo',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalsubcategoria',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalsubcategoria',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='historicalsubcategoria',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsubcategoria',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='puestotrabajo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='puestotrabajo',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='puestotrabajo',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sistemaoperativo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sistemaoperativo',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='sistemaoperativo',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='sistema_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_tic.licenciaos'),
        ),
        migrations.AlterField(
            model_name='historicalequipo',
            name='sistema_operativo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion_tic.licenciaos'),
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['nombre'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='jefetic',
            options={'ordering': ['nombre'], 'verbose_name': 'JefeTic', 'verbose_name_plural': 'JefesTic'},
        ),
        migrations.AlterModelOptions(
            name='licenciaos',
            options={'ordering': ['nombre'], 'verbose_name': 'Licencia de Sistema Operativo', 'verbose_name_plural': 'Licencias de Sistema Operativo'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['nombre'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='microsoftoffice',
            options={'ordering': ['nombre'], 'verbose_name': 'Licencia de Microsoft Office', 'verbose_name_plural': 'Licencias de Microsoft Office'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'ordering': ['nombre'], 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={'ordering': ['nombre'], 'verbose_name': 'Propietario de Dispositivo', 'verbose_name_plural': 'Propietarios de Dispositivo'},
        ),
        migrations.AlterModelOptions(
            name='tipocelular',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo Celular', 'verbose_name_plural': 'Tipos Celular'},
        ),
        migrations.AlterModelOptions(
            name='tipocomputador',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo Computador', 'verbose_name_plural': 'Tipos Computador'},
        ),
        migrations.AlterModelOptions(
            name='tipoimpresora',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo Impresora', 'verbose_name_plural': 'Tipos Impresoras'},
        ),
        migrations.AlterModelOptions(
            name='toner',
            options={'ordering': ['nombre'], 'verbose_name': 'Tinta', 'verbose_name_plural': 'Tintas'},
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='HistoricalCategoria',
        ),
        migrations.DeleteModel(
            name='HistoricalPuestoTrabajo',
        ),
        migrations.DeleteModel(
            name='HistoricalSistemaOperativo',
        ),
        migrations.DeleteModel(
            name='HistoricalSubCategoria',
        ),
        migrations.DeleteModel(
            name='PuestoTrabajo',
        ),
        migrations.DeleteModel(
            name='SistemaOperativo',
        ),
        migrations.DeleteModel(
            name='SubCategoria',
        ),
    ]
