# Generated by Django 6.0.7 on 2026-07-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0006_historicalips_gateway_historicalips_mascara_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campotipoactivo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalcampotipoactivo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='campotipoactivo',
            name='codigo',
        ),
    ]
