# Generated by Django 6.0.7 on 2026-07-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0008_remove_historicalmicrosoftoffice_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campotipoactivo',
            name='codigo',
            field=models.SlugField(default='', help_text='Código interno para identificar el campo (ej: memoria_ram)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcampotipoactivo',
            name='codigo',
            field=models.SlugField(default='', help_text='Código interno para identificar el campo (ej: memoria_ram)', max_length=100),
            preserve_default=False,
        ),
    ]
