# Generated by Django 6.0.6 on 2026-07-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0009_campotipoactivo_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campotipoactivo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='historicalcampotipoactivo',
            name='codigo',
        ),
    ]
