# Generated by Django 6.0.6 on 2026-07-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0010_remove_campotipoactivo_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activo',
            options={'ordering': ['codigo_barra']},
        ),
        migrations.RemoveField(
            model_name='activo',
            name='numero_inventario',
        ),
        migrations.RemoveField(
            model_name='historicalactivo',
            name='numero_inventario',
        ),
    ]
