# Generated by Django 6.0.7 on 2026-07-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0011_alter_activo_options_remove_activo_numero_inventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_tic.contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contratos/%Y'),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='contrato',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion_tic.contrato'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
