# Generated by Django 6.0.7 on 2026-08-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0012_activo_contrato_contrato_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltipomovimiento',
            name='color',
        ),
        migrations.RemoveField(
            model_name='historicaltipomovimiento',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='tipomovimiento',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tipomovimiento',
            name='icono',
        ),
    ]
