# Generated by Django 6.0.7 on 2026-08-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0013_remove_historicaltipomovimiento_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gestion_tic/documentos/contratos/%Y'),
        ),
    ]
