# Generated by Django 6.0.6 on 2026-08-14 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0014_alter_contrato_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activocaracteristica',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tic.campotipoactivo'),
        ),
    ]
