# Generated by Django 6.0.7 on 2026-08-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0015_alter_activocaracteristica_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovimientoactivo',
            name='jefe_firmante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion_tic.jefetic'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='jefe_firmante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_tic.jefetic'),
        ),
    ]
