# Generated by Django 6.0.7 on 2026-09-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0016_historicalmovimientoactivo_jefe_firmante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='utiliza_ip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='utiliza_ip',
            field=models.BooleanField(default=False),
        ),
    ]
