# Generated by Django 6.0.7 on 2026-09-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0017_activo_utiliza_ip_historicalactivo_utiliza_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='utiliza_ip',
            field=models.BooleanField(default=False, verbose_name='¿El activo usa IP?'),
        ),
        migrations.AlterField(
            model_name='historicalactivo',
            name='utiliza_ip',
            field=models.BooleanField(default=False, verbose_name='¿El activo usa IP?'),
        ),
    ]
