# Generated by Django 6.0.7 on 2026-10-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0018_alter_activo_utiliza_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovimientoactivo',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmovimientoactivo',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
