# Generated by Django 6.0.7 on 2026-10-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tic', '0019_historicalmovimientoactivo_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovimientoactivo',
            name='recepcionado',
            field=models.BooleanField(default=False, verbose_name='Recepcionado'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='recepcionado',
            field=models.BooleanField(default=False, verbose_name='Recepcionado'),
        ),
    ]
