# Generated by Django 6.0.7 on 2026-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_correo', '0002_historicalperfilcorreo_perfilcorreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperfilcorreo',
            name='bandeja_rrhh',
            field=models.IntegerField(choices=[(0, 'Sin Acceso'), (1, 'Solo Ver'), (2, 'Crear y Modificar'), (3, 'Administrador')], default=0, verbose_name='Bandeja RR.HH.'),
        ),
        migrations.AlterField(
            model_name='historicalperfilcorreo',
            name='bandeja_tic',
            field=models.IntegerField(choices=[(0, 'Sin Acceso'), (1, 'Solo Ver'), (2, 'Crear y Modificar'), (3, 'Administrador')], default=0, verbose_name='Bandeja TIC'),
        ),
        migrations.AlterField(
            model_name='perfilcorreo',
            name='bandeja_rrhh',
            field=models.IntegerField(choices=[(0, 'Sin Acceso'), (1, 'Solo Ver'), (2, 'Crear y Modificar'), (3, 'Administrador')], default=0, verbose_name='Bandeja RR.HH.'),
        ),
        migrations.AlterField(
            model_name='perfilcorreo',
            name='bandeja_tic',
            field=models.IntegerField(choices=[(0, 'Sin Acceso'), (1, 'Solo Ver'), (2, 'Crear y Modificar'), (3, 'Administrador')], default=0, verbose_name='Bandeja TIC'),
        ),
    ]
