"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.urls import reverse_lazy
from dotenv import load_dotenv

from config import db

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if host.strip()]
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in
                        os.getenv('CSRF_TRUSTED_ORIGINS', 'http://127.0.0.1,http://localhost').split(',') if
                        origin.strip()]

FORCE_SCRIPT_NAME = os.getenv('FORCE_SCRIPT_NAME', '')
if FORCE_SCRIPT_NAME == '':
    FORCE_SCRIPT_NAME = None

AUTH_USER_MODEL = 'core.User'
LOGIN_URL = reverse_lazy('login')
LOGIN_REDIRECT_URL = reverse_lazy('intranet:index')
LOGOUT_REDIRECT_URL = reverse_lazy('login')

SIMPLE_HISTORY_HISTORY_ID_USE_UUID = False

SESSION_COOKIE_NAME = os.getenv('SESSION_COOKIE_NAME') or 'sessionid'
CSRF_COOKIE_NAME = os.getenv('CSRF_COOKIE_NAME') or 'csrftoken'
#
SESSION_COOKIE_PATH = os.getenv('SESSION_COOKIE_PATH', '/')
CSRF_COOKIE_PATH = os.getenv('CSRF_COOKIE_PATH', '/')

SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'

SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')

#
USE_X_FORWARDED_HOST = os.getenv('USE_X_FORWARDED_HOST', 'True') == 'True'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')
# Configuración de sesiones
SESSION_COOKIE_AGE = 3600  # 1 hora por defecto
SESSION_SAVE_EVERY_REQUEST = True  # Para que la inactividad se cuente desde la última petición
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Por defecto expira al cerrar el navegador si no se dice lo contrario

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'colorfield',
    'simple_history',
    'import_export',
    'django_select2',
    'core.apps.CoreConfig',
    'agenda_telefonica.apps.AgendaTelefonicaConfig',
    'soporte.apps.SoporteConfig',
]

X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'ALLOWALL')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'agenda_telefonica.context_processors.menu_sidebar',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_TYPE = os.getenv('DB_TYPE', 'SQLITE')

if DB_TYPE == 'POSTGRESQL':
    DATABASES = db.POSTGRESQL
elif DB_TYPE == 'MYSQL':
    DATABASES = db.MYSQL
else:
    DATABASES = db.SQLITE

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'es-es')

TIME_ZONE = os.getenv('TIME_ZONE', 'America/Santiago')

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = os.getenv('STATIC_URL', '/static/')
STATIC_ROOT = BASE_DIR / 'staticfiles'
