# Generated by Django 6.0.7 on 2026-08-05 09:13

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='color',
            field=colorfield.fields.ColorField(default='#006FB3', image_field=None, max_length=25, samples=[('#006FB3', 'Primary (Azul)'), ('#7F8F99', 'Secondary (Gris)'), ('#3fa1ad', 'Success (Verde)'), ('#876bbe', 'Info (Morado)'), ('#FFA11B', 'Warning (Naranja)'), ('#1976D2', 'Azul Corporativo'), ('#1565C0', 'Azul Oscuro'), ('#0097A7', 'Turquesa'), ('#2E7D32', 'Verde'), ('#43A047', 'Verde Claro'), ('#7CB342', 'Lima'), ('#F57C00', 'Naranjo'), ('#FFB300', 'Ámbar'), ('#D32F2F', 'Rojo'), ('#C62828', 'Burdeo'), ('#8E24AA', 'Morado'), ('#5E35B1', 'Violeta'), ('#3949AB', 'Índigo'), ('#455A64', 'Gris Oscuro'), ('#607D8B', 'Gris')]),
        ),
        migrations.AddField(
            model_name='bodega',
            name='icono',
            field=models.TextField(blank=True, default='\n        <svg class="small-box-icon" fill="currentColor" viewBox="0 0 24 24"\n             xmlns="http://www.w3.org/2000/svg" aria-hidden="true">\n            <path fill-rule="evenodd" clip-rule="evenodd"\n                  d="M11.47 2.47a1.5 1.5 0 011.06 0l7.5 3A1.5 1.5 0 0121 6.86v10.28a1.5 1.5 0 01-.94 1.39l-7.5 3a1.5 1.5 0 01-1.12 0l-7.5-3A1.5 1.5 0 013 17.14V6.86a1.5 1.5 0 01.94-1.39l7.5-3zM12 3.94 5.2 6.66 12 9.38l6.8-2.72L12 3.94zm7.5 4.33-6.75 2.7v8.28l6.75-2.7V8.27zm-8.25 11V10.97L4.5 8.27v8.28l6.75 2.7z"/>\n        </svg>\n        ', help_text='\n            <p><strong>Formato esperado:</strong></p>\n\n            <pre style="background:#f5f5f5;padding:10px;border-radius:4px;overflow:auto;">\n        &lt;svg class="small-box-icon" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"&gt;\n            &lt;path d="PEGAR_AQUI_EL_PATH"/&gt;\n        &lt;/svg&gt;\n            </pre>\n\n            <p>\n                Solo debe reemplazar el valor del atributo <code>d</code> del elemento\n                <code>&lt;path&gt;</code>.\n            </p>\n\n            <p>\n                Puede obtener el <strong>path</strong> desde\n                <a href="https://heroicons.com/" target="_blank">Heroicons</a>\n                (copiando únicamente el contenido del atributo <code>d</code>).\n            </p>\n            '),
        ),
        migrations.AddField(
            model_name='bodega',
            name='texto_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=[('#ffffff', 'Blanco'), ('#000000', 'Negro')], verbose_name='Color de texto'),
        ),
        migrations.AddField(
            model_name='historicalbodega',
            name='color',
            field=colorfield.fields.ColorField(default='#006FB3', image_field=None, max_length=25, samples=[('#006FB3', 'Primary (Azul)'), ('#7F8F99', 'Secondary (Gris)'), ('#3fa1ad', 'Success (Verde)'), ('#876bbe', 'Info (Morado)'), ('#FFA11B', 'Warning (Naranja)'), ('#1976D2', 'Azul Corporativo'), ('#1565C0', 'Azul Oscuro'), ('#0097A7', 'Turquesa'), ('#2E7D32', 'Verde'), ('#43A047', 'Verde Claro'), ('#7CB342', 'Lima'), ('#F57C00', 'Naranjo'), ('#FFB300', 'Ámbar'), ('#D32F2F', 'Rojo'), ('#C62828', 'Burdeo'), ('#8E24AA', 'Morado'), ('#5E35B1', 'Violeta'), ('#3949AB', 'Índigo'), ('#455A64', 'Gris Oscuro'), ('#607D8B', 'Gris')]),
        ),
        migrations.AddField(
            model_name='historicalbodega',
            name='icono',
            field=models.TextField(blank=True, default='\n        <svg class="small-box-icon" fill="currentColor" viewBox="0 0 24 24"\n             xmlns="http://www.w3.org/2000/svg" aria-hidden="true">\n            <path fill-rule="evenodd" clip-rule="evenodd"\n                  d="M11.47 2.47a1.5 1.5 0 011.06 0l7.5 3A1.5 1.5 0 0121 6.86v10.28a1.5 1.5 0 01-.94 1.39l-7.5 3a1.5 1.5 0 01-1.12 0l-7.5-3A1.5 1.5 0 013 17.14V6.86a1.5 1.5 0 01.94-1.39l7.5-3zM12 3.94 5.2 6.66 12 9.38l6.8-2.72L12 3.94zm7.5 4.33-6.75 2.7v8.28l6.75-2.7V8.27zm-8.25 11V10.97L4.5 8.27v8.28l6.75 2.7z"/>\n        </svg>\n        ', help_text='\n            <p><strong>Formato esperado:</strong></p>\n\n            <pre style="background:#f5f5f5;padding:10px;border-radius:4px;overflow:auto;">\n        &lt;svg class="small-box-icon" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"&gt;\n            &lt;path d="PEGAR_AQUI_EL_PATH"/&gt;\n        &lt;/svg&gt;\n            </pre>\n\n            <p>\n                Solo debe reemplazar el valor del atributo <code>d</code> del elemento\n                <code>&lt;path&gt;</code>.\n            </p>\n\n            <p>\n                Puede obtener el <strong>path</strong> desde\n                <a href="https://heroicons.com/" target="_blank">Heroicons</a>\n                (copiando únicamente el contenido del atributo <code>d</code>).\n            </p>\n            '),
        ),
        migrations.AddField(
            model_name='historicalbodega',
            name='texto_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=[('#ffffff', 'Blanco'), ('#000000', 'Negro')], verbose_name='Color de texto'),
        ),
    ]
