# Generated by Django 6.0.6 on 2026-08-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_bodega_color_bodega_icono_bodega_texto_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='stock_actual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='stock_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_actual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
