# Generated by Django 6.0.7 on 2026-08-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_alter_historicalstock_stock_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='stock_actual',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='stock_maximo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='stock_minimo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_actual',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_maximo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_minimo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
