# Generated by Django 6.0.6 on 2026-08-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_alter_historicalstock_stock_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmovimientoinventario',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
