# Generated by Django 6.0.7 on 2026-10-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_vpn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesovpn',
            old_name='ip_o_segmento',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='historicalaccesovpn',
            old_name='ip_o_segmento',
            new_name='ip',
        ),
        migrations.RemoveField(
            model_name='accesovpn',
            name='beneficiario',
        ),
        migrations.RemoveField(
            model_name='accesovpn',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='accesovpn',
            name='puerto',
        ),
        migrations.RemoveField(
            model_name='accesovpn',
            name='timeout_vpn',
        ),
        migrations.RemoveField(
            model_name='accesovpn',
            name='tipo_acceso',
        ),
        migrations.RemoveField(
            model_name='historicalaccesovpn',
            name='beneficiario',
        ),
        migrations.RemoveField(
            model_name='historicalaccesovpn',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='historicalaccesovpn',
            name='puerto',
        ),
        migrations.RemoveField(
            model_name='historicalaccesovpn',
            name='timeout_vpn',
        ),
        migrations.RemoveField(
            model_name='historicalaccesovpn',
            name='tipo_acceso',
        ),
        migrations.RemoveField(
            model_name='historicalperfilvpn',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='perfilvpn',
            name='fecha',
        ),
    ]
