# Generated by Django 6.1 on 2026-10-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_vpn', '0002_rename_ip_o_segmento_accesovpn_ip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesovpn',
            options={'ordering': ['plataforma', 'ip'], 'verbose_name': 'Acceso VPN', 'verbose_name_plural': 'Accesos VPN'},
        ),
        migrations.AddField(
            model_name='solicitudvpn',
            name='accesos',
            field=models.ManyToManyField(blank=True, related_name='solicitudes_vpn', to='solicitud_vpn.accesovpn', verbose_name='Accesos VPN'),
        ),
    ]
