# Generated by Django 6.0.6 on 2026-06-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='nombre_cliente',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='nombre_cliente',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
