# Generated by Django 6.0.7 on 2026-07-29 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracioncorreo_recuperacionpassword'),
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperfilsoporte',
            name='funcionario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.funcionario'),
        ),
        migrations.AddField(
            model_name='perfilsoporte',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario'),
        ),
    ]
