# Generated by Django 6.0.7 on 2026-07-31 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperfilsoporte',
            name='usuario_soporte',
        ),
        migrations.RemoveField(
            model_name='perfilsoporte',
            name='usuario_soporte',
        ),
        migrations.AddField(
            model_name='perfilsoporte',
            name='area_soporte',
            field=models.ManyToManyField(blank=True, to='soporte.areasoporte', verbose_name='Areas de Soporte'),
        ),
        migrations.AlterField(
            model_name='historicalperfilsoporte',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='perfilsoporte',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_soporte', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
