# Generated by Django 6.0.7 on 2026-08-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_remove_historicalperfilsoporte_usuario_soporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='area_soporte',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='soporte.areasoporte', verbose_name='Area de Soporte'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='area_soporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soporte.areasoporte', verbose_name='Area de Soporte'),
        ),
    ]
