# Generated by Django 6.0.6 on 2026-06-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_historicalticket_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='nombre_cliente',
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='correo_funcionario',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='nombre_funcionario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='correo_funcionario',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nombre_funcionario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
