# Generated by Django 6.0.6 on 2026-06-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0003_remove_historicalticket_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='nombre_servicio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nombre_servicio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
