# Generated by Django 6.0.6 on 2026-06-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0004_historicalticket_nombre_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='funcionario',
        ),
    ]
