# Generated by Django 6.0 on 2026-08-26 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0004_alter_ticket_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='asignado_a',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='soporte.perfilsoporte'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='soporte.perfilsoporte'),
        ),
    ]
