# Generated by Django 6.0.7 on 2026-09-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0005_alter_historicalticket_asignado_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposoporte',
            name='area_soporte',
            field=models.ManyToManyField(blank=True, null=True, to='soporte.areasoporte', verbose_name='Areas de Soporte'),
        ),
    ]
