# Generated by Django 6.0.6 on 2026-06-25 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0006_historicalperfilsoporte_perfilsoporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='correo_funcionario',
        ),
        migrations.RemoveField(
            model_name='historicalticket',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='historicalticket',
            name='nombre_funcionario',
        ),
        migrations.RemoveField(
            model_name='historicalticket',
            name='nombre_servicio',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='correo_funcionario',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='nombre_funcionario',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='nombre_servicio',
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='funcionario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalperfilsoporte',
            name='usuario_soporte',
            field=models.BooleanField(default=True, verbose_name='¿Solicita Soporte?'),
        ),
        migrations.AlterField(
            model_name='perfilsoporte',
            name='usuario_soporte',
            field=models.BooleanField(default=True, verbose_name='¿Solicita Soporte?'),
        ),
    ]
