# Generated by Django 6.1 on 2026-09-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0006_tiposoporte_area_soporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='apellidos',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='correo',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='departamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='nombres',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='apellidos',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='correo',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='departamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nombres',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='tiposoporte',
            name='area_soporte',
            field=models.ManyToManyField(blank=True, to='soporte.areasoporte', verbose_name='Areas de Soporte'),
        ),
    ]
