# Generated by Django 6.0.6 on 2026-06-26 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0007_remove_historicalticket_correo_funcionario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperfilsoporte',
            name='usuario',
        ),
        migrations.AddField(
            model_name='historicalperfilsoporte',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilsoporte',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='perfilsoporte',
            name='usuario',
        ),
        migrations.AddField(
            model_name='perfilsoporte',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
