# Generated by Django 6.0.7 on 2026-09-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0007_historicalticket_apellidos_historicalticket_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En Proceso'), ('ESPERA', 'En Espera'), ('CERRADO', 'Cerrado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En Proceso'), ('ESPERA', 'En Espera'), ('CERRADO', 'Cerrado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=20),
        ),
    ]
