# Generated by Django 6.0.6 on 2026-06-26 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0008_remove_historicalperfilsoporte_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='numero_ticket',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfilsoporte',
            name='usuario',
            field=models.ManyToManyField(blank=True, related_name='perfil_soporte_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='numero_ticket',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
