# Generated by Django 6.0.6 on 2026-06-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_historicaluser_departamento_user_departamento'),
        ('soporte', '0009_alter_historicalticket_numero_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='departamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.departamento'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.departamento'),
        ),
    ]
