# Generated by Django 6.0.6 on 2026-06-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0011_historicalticketconfig_ticketconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperfilsoporte',
            name='es_editor',
            field=models.BooleanField(default=False, verbose_name='¿Es Editor?'),
        ),
        migrations.AddField(
            model_name='perfilsoporte',
            name='es_editor',
            field=models.BooleanField(default=False, verbose_name='¿Es Editor?'),
        ),
    ]
