# Generated by Django 6.0.6 on 2026-06-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0012_historicalperfilsoporte_es_editor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperfilsoporte',
            name='es_editor',
        ),
        migrations.RemoveField(
            model_name='perfilsoporte',
            name='es_editor',
        ),
    ]
