# Generated by Django 6.0.6 on 2026-07-06 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0013_remove_historicalperfilsoporte_es_editor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperfilsoporte',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='perfilsoporte',
            name='nombre',
        ),
        migrations.AddField(
            model_name='historicalperfilsoporte',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='perfilsoporte',
            name='usuario',
        ),
        migrations.AddField(
            model_name='perfilsoporte',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_soporte', to=settings.AUTH_USER_MODEL),
        ),
    ]
