# Generated by Django 6.0.6 on 2026-07-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0015_alter_perfilsoporte_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='departamento',
        ),
    ]
