# Generated by Django 6.0.6 on 2026-07-14 22:48

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('anexo', models.CharField(max_length=6, verbose_name='Anexo')),
                ('anexo_publico', models.CharField(blank=True, max_length=20, null=True, verbose_name='Anexo Público')),
                ('numero_telefonico', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Telefónico Institucional')),
                ('nombre_anexo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre Anexo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('encargado_de', models.CharField(blank=True, max_length=200, null=True, verbose_name='Encargado/a de')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-anexo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAnexo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('anexo', models.CharField(max_length=6, verbose_name='Anexo')),
                ('anexo_publico', models.CharField(blank=True, max_length=20, null=True, verbose_name='Anexo Público')),
                ('numero_telefonico', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Telefónico Institucional')),
                ('nombre_anexo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre Anexo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('encargado_de', models.CharField(blank=True, max_length=200, null=True, verbose_name='Encargado/a de')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Anexo',
                'verbose_name_plural': 'historical Anexos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMenuSidebar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('mostrar', models.BooleanField(default=True, verbose_name='Mostrar en menú')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical menu sidebar',
                'verbose_name_plural': 'historical menu sidebars',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPerfilAgenda',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('editor', models.BooleanField(default=True, verbose_name='Editor')),
                ('mantenedores', models.BooleanField(default=False, verbose_name='¿Acceso a Mantenedores?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical perfil agenda',
                'verbose_name_plural': 'historical perfil agendas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MenuSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('mostrar', models.BooleanField(default=True, verbose_name='Mostrar en menú')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('editor', models.BooleanField(default=True, verbose_name='Editor')),
                ('mantenedores', models.BooleanField(default=False, verbose_name='¿Acceso a Mantenedores?')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
