# Generated by Django 6.0.6 on 2026-06-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='active',
        ),
        migrations.AlterField(
            model_name='anexo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
