# Generated by Django 6.0.6 on 2026-06-23 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0002_remove_anexo_active_alter_anexo_is_active'),
        ('core', '0004_departamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexo',
            options={'ordering': ['nombre'], 'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'},
        ),
        migrations.CreateModel(
            name='MenuSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('mostrar', models.BooleanField(default=True, verbose_name='Mostrar en menú')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.establecimiento', verbose_name='Establecimiento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
