# Generated by Django 6.0.7 on 2026-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0003_alter_anexo_anexo_alter_historicalanexo_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='anexo',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='historicalanexo',
            name='anexo',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Anexo'),
        ),
    ]
