# Generated by Django 6.0.6 on 2026-06-23 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0004_direccion_historicalanexo_historicaldireccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda_telefonica.direccion', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='historicalanexo',
            name='direccion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agenda_telefonica.direccion', verbose_name='Dirección'),
        ),
    ]
