# Generated by Django 6.0.6 on 2026-06-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0007_historicalservicio_servicio'),
        ('core', '0007_alter_departamento_establecimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='anexo',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='historicalanexo',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='historicalanexo',
            name='direccion',
        ),
        migrations.AddField(
            model_name='anexo',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda_telefonica.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalanexo',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalanexo',
            name='servicio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agenda_telefonica.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='historicaldireccion',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalubicacion',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='core.establecimiento', verbose_name='Establecimiento'),
        ),
    ]
