# Generated by Django 6.0.6 on 2026-06-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0008_remove_anexo_departamento_remove_anexo_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?'),
        ),
        migrations.AlterField(
            model_name='historicalanexo',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?'),
        ),
    ]
