# Generated by Django 6.0.6 on 2026-07-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0010_historicalperfilagenda_perfilagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperfilagenda',
            name='mantenedores',
            field=models.BooleanField(default=False, verbose_name='¿Acceso a Mantenedores?'),
        ),
        migrations.AddField(
            model_name='perfilagenda',
            name='mantenedores',
            field=models.BooleanField(default=False, verbose_name='¿Acceso a Mantenedores?'),
        ),
    ]
