# Generated by Django 6.0.6 on 2026-07-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0012_cargo_historicalperfilagenda_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperfilagenda',
            name='cargo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agenda_telefonica.nivelorganizacional'),
        ),
        migrations.AlterField(
            model_name='perfilagenda',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='agenda_telefonica.nivelorganizacional'),
        ),
    ]
