# Generated by Django 6.0.6 on 2026-07-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0013_alter_historicalperfilagenda_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperfilagenda',
            name='jefatura',
            field=models.BooleanField(default=False, verbose_name='¿Es Jefatura?'),
        ),
        migrations.AddField(
            model_name='historicalperfilagenda',
            name='posicion_subrrogante',
            field=models.IntegerField(default=0, help_text='Si le dió Checka es subrrogante entonces indique la posición', verbose_name='Posición de subrogante'),
        ),
        migrations.AddField(
            model_name='historicalperfilagenda',
            name='subrrogante',
            field=models.BooleanField(default=False, verbose_name='¿Es subrrogante?'),
        ),
        migrations.AddField(
            model_name='perfilagenda',
            name='jefatura',
            field=models.BooleanField(default=False, verbose_name='¿Es Jefatura?'),
        ),
        migrations.AddField(
            model_name='perfilagenda',
            name='posicion_subrrogante',
            field=models.IntegerField(default=0, help_text='Si le dió Checka es subrrogante entonces indique la posición', verbose_name='Posición de subrogante'),
        ),
        migrations.AddField(
            model_name='perfilagenda',
            name='subrrogante',
            field=models.BooleanField(default=False, verbose_name='¿Es subrrogante?'),
        ),
    ]
