# Generated by Django 6.0.6 on 2026-07-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0015_alter_anexo_created_by_alter_anexo_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='historicaldireccion',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='historicalubicacion',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='establecimiento',
        ),
    ]
