# Generated by Django 6.0.6 on 2026-07-12 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0017_remove_direccion_created_by_and_more'),
        ('core', '0032_alter_funcionario_options_remove_funcionario_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexo',
            options={'ordering': ['-anexo'], 'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'},
        ),
        migrations.RemoveField(
            model_name='anexo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='anexo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='historicalanexo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalanexo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='anexo',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario', verbose_name='Funcionario'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='numero_telefonico',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Telefónico'),
        ),
        migrations.AddField(
            model_name='historicalanexo',
            name='funcionario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.funcionario', verbose_name='Funcionario'),
        ),
        migrations.AddField(
            model_name='historicalanexo',
            name='numero_telefonico',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Telefónico'),
        ),
    ]
