# Generated by Django 6.0.6 on 2026-07-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('agenda_telefonica', '0018_alter_anexo_options_remove_anexo_email_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='historicalperfilagenda',
        #     name='jefatura',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalperfilagenda',
        #     name='posicion_subrrogante',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalperfilagenda',
        #     name='subrrogante',
        # ),
        # migrations.RemoveField(
        #     model_name='perfilagenda',
        #     name='jefatura',
        # ),
        # migrations.RemoveField(
        #     model_name='perfilagenda',
        #     name='posicion_subrrogante',
        # ),
        # migrations.RemoveField(
        #     model_name='perfilagenda',
        #     name='subrrogante',
        # ),
        migrations.AlterField(
            model_name='anexo',
            name='anexo',
            field=models.CharField(max_length=6, unique=True, verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='historicalanexo',
            name='anexo',
            field=models.CharField(db_index=True, max_length=6, verbose_name='Anexo'),
        ),
    ]
