# Generated by Django 6.0.6 on 2026-07-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0019_remove_historicalperfilagenda_jefatura_and_more'),
        ('core', '0032_alter_funcionario_options_remove_funcionario_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilagenda',
            name='unidad_organizacional',
            field=models.ManyToManyField(blank=True, null=True, to='core.unidadorganizacional', verbose_name='Unidad Organizacional'),
        ),
    ]
