# Generated by Django 6.0.6 on 2026-07-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0020_perfilagenda_unidad_organizacional'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilagenda',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Grupos'),
        ),
    ]
