# Generated by Django 6.0.6 on 2026-07-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0022_alter_perfilagenda_unidad_organizacional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilagenda',
            name='grupos',
        ),
    ]
