# Generated by Django 6.0.6 on 2026-07-13 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0023_remove_perfilagenda_grupos'),
        ('core', '0033_alter_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='funcionario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario', verbose_name='Funcionario'),
        ),
    ]
