# Generated by Django 6.0.6 on 2026-07-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0024_alter_anexo_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='numero_telefonico',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Telefónico Institucional'),
        ),
        migrations.AlterField(
            model_name='historicalanexo',
            name='numero_telefonico',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Telefónico Institucional'),
        ),
    ]
