# Generated by Django 6.0.6 on 2026-07-14 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0025_alter_anexo_numero_telefonico_and_more'),
        ('core', '0038_remove_historicalubicacion_enlace_google_maps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='encargado_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Encargado de'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='nombre_anexo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre Anexo'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='rol_organizacional',
            field=models.ForeignKey(blank=True, help_text='Jefe, Subrogante, Coordinador, Encargado, etc.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='core.rolorganizacional', verbose_name='Puesto'),
        ),
        migrations.AddField(
            model_name='historicalanexo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='historicalanexo',
            name='encargado_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Encargado de'),
        ),
        migrations.AddField(
            model_name='historicalanexo',
            name='nombre_anexo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre Anexo'),
        ),
        migrations.AddField(
            model_name='historicalanexo',
            name='rol_organizacional',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Jefe, Subrogante, Coordinador, Encargado, etc.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.rolorganizacional', verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='anexo',
            field=models.CharField(max_length=6, verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='historicalanexo',
            name='anexo',
            field=models.CharField(max_length=6, verbose_name='Anexo'),
        ),
    ]
