# Generated by Django 6.0.6 on 2026-07-14 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0026_anexo_email_anexo_encargado_de_anexo_nombre_anexo_and_more'),
        ('core', '0038_remove_historicalubicacion_enlace_google_maps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='unidad_organizacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unidadorganizacional', verbose_name='Unidad Organizacional'),
        ),
        migrations.AddField(
            model_name='historicalanexo',
            name='unidad_organizacional',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.unidadorganizacional', verbose_name='Unidad Organizacional'),
        ),
    ]
