# Generated by Django 6.0.6 on 2026-07-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_telefonica', '0027_anexo_unidad_organizacional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='encargado_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Encargado/a de'),
        ),
        migrations.AlterField(
            model_name='historicalanexo',
            name='encargado_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Encargado/a de'),
        ),
    ]
